### ISSUE TITLE
Options vide

### ISSUE THREAD

**Issue by StrangeBlackHole** [zzuutt/CustomerValidation#1]
Salut,

dans le formulaire d'édition d'un client, la liste status est vide. Enfin elle comporte bien les 3 options mais pas le texte qui va avec.

```
<select id="status" name="thelia_customer_update[status]" class="form-control " aria-required="true" required="">
  <option value="1"></option>
  <option value="2"></option>
  <option value="3"></option>
</select>
```

**Comment by zzuutt** [comment]
Salut,
De mon coté tout fonctionne, avec la langue FR et EN. 
tu utilises le back avec quelle langue ?

**Comment by StrangeBlackHole** [comment]
Hello, je l'utilise en EN.

**Comment by zzuutt** [comment]
j'ai trouvé le bug je publie le correctif
erreur dans la table de traduc j'ai mis en_EN alors que cela doit être en_US

**Comment by StrangeBlackHole** [comment]
Merci beaucoup @zzuutt pour ta réactivité 

;) Fabrice

**Comment by zzuutt** [comment]
tu peux mettre à jour
