### ISSUE TITLE
SQLSTATE[23000]: à l'Update ou à l'install

### ISSUE THREAD

**Issue by StrangeBlackHole** [zzuutt/CustomerValidation#3]
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'waiting' for key 'code_UNIQUE'

désolé...

**Comment by zzuutt** [comment]
ne tiens pas compte de l'erreur, normalement la mise à jour a été faite.
vérifies que la version est passée en 0.5

**Comment by StrangeBlackHole** [comment]
il est bien indiqué en 0.5 mais ne s'active pas. Si je l'active, il présente l'erreur SQL, je l'active une seconde fois, il passe bien en vert mais si je vais sur customers, pas de status et quand je reviens sur modules, il est désactivé.

**Comment by zzuutt** [comment]
c'est corrigé, de mon coté ça passe.
tu peux mettre à jour v0.6

**Comment by StrangeBlackHole** [comment]
Ok, alors de mon coté pour contourner voici comment j'ai fait.

j'ai supprimé le module et les tables correspondantes (à la main car pas de destroy.sql). Puis en faisant une nouvelle install propre ça passe sans problème.

Je test la mise à jour v0.6 pour te faire un retour utilisateur.

**Comment by StrangeBlackHole** [comment]
Ok, bonne pioche la mise à jour passe nickel.
Tu peux fermer le ticket.

merci à toi ;)
